// src/lean/transpiler.ts
//
// Translates a FuturLang AST into a Lean 4 source file.
//
// Strategy:
//   - theorem block  → theorem signature (the proposition)
//   - proof block    → by { tactic block }
//   - theorem ↔ proof → theorem Name : <sig> := by { <tactics> }
//   - assert inside theorem → becomes the type
//   - assert inside proof   → have : <expr> := by <tactic>
//   - assume inside proof   → intro / have hypothesis
//   - setVar               → intro or let binding
//   - conclude             → exact / decide
//
// Math notation rewriting:
//   ∀(x: T) ⇒   →  ∀ x : T,
//   ∃(x: T) ⇒   →  ∃ x : T,
//   →            →  →   (same in Lean)
//   ↔            →  ↔
//   ∧            →  ∧
//   ∨            →  ∨
//   ¬            →  ¬
//   ℝ ℕ ℤ ℚ      →  ℝ ℕ ℤ ℚ  (same)
//   |G|          →  Finset.card G  (or G.card)
//   divides      →  ∣
//   ...anything untranslatable → sorry

import {
  ASTNode, TheoremNode, ProofNode, LemmaNode, DefinitionNode,
  StructNode, AssertNode, AssumeNode, ConcludeNode, SetVarNode,
  ApplyNode, RawNode, ExprNode, AtomNode,
} from '../parser/ast';

export interface LeanOutput {
  source: string;       // full .lean file contents
  theoremNames: string[]; // for `lake build` targeting
}

export function transpileToLean(nodes: ASTNode[]): LeanOutput {
  const theoremNames: string[] = [];
  const sections: string[] = [];

  sections.push('-- Auto-generated by FuturLang. Do not edit.');
  sections.push('import Mathlib');
  sections.push('');

  // Find theorem↔proof pairs and standalone theorems
  const paired = pairTheoremProofs(nodes);

  for (const item of paired) {
    if (item.type === 'theorem_proof') {
      const lean = translateTheoremProof(item.theorem, item.proof);
      sections.push(lean);
      theoremNames.push(leanName(item.theorem.name));
    } else if (item.type === 'theorem_only') {
      const lean = translateTheoremOnly(item.theorem);
      sections.push(lean);
      theoremNames.push(leanName(item.theorem.name));
    } else if (item.type === 'lemma_proof') {
      const lean = translateLemmaProof(item.lemma, item.proof);
      sections.push(lean);
    } else if (item.type === 'definition') {
      sections.push(translateDefinition(item.definition));
    } else if (item.type === 'struct') {
      sections.push(translateStruct(item.struct));
    }
  }

  return { source: sections.join('\n'), theoremNames };
}

// ── Pair theorem nodes with their proof nodes ────────────────────────────────
// In FuturLang: theorem X() { ... } ↔ proof X() { ... }
// The ↔ connective on the theorem block signals it pairs with the next proof.

type PairedItem =
  | { type: 'theorem_proof'; theorem: TheoremNode; proof: ProofNode }
  | { type: 'theorem_only'; theorem: TheoremNode }
  | { type: 'lemma_proof'; lemma: LemmaNode; proof: ProofNode }
  | { type: 'definition'; definition: DefinitionNode }
  | { type: 'struct'; struct: StructNode };

function pairTheoremProofs(nodes: ASTNode[]): PairedItem[] {
  const items: PairedItem[] = [];
  let i = 0;

  while (i < nodes.length) {
    const node = nodes[i];

    if (node.type === 'Theorem') {
      // If connected via ↔ to the next proof, pair them
      if (node.connective === '↔' && i + 1 < nodes.length && nodes[i + 1].type === 'Proof') {
        const proof = nodes[i + 1] as ProofNode;
        items.push({ type: 'theorem_proof', theorem: node, proof });
        i += 2;
      } else {
        items.push({ type: 'theorem_only', theorem: node });
        i++;
      }
    } else if (node.type === 'Lemma') {
      if (node.connective === '↔' && i + 1 < nodes.length && nodes[i + 1].type === 'Proof') {
        const proof = nodes[i + 1] as ProofNode;
        items.push({ type: 'lemma_proof', lemma: node, proof });
        i += 2;
      } else {
        i++;
      }
    } else if (node.type === 'Definition') {
      items.push({ type: 'definition', definition: node });
      i++;
    } else if (node.type === 'Struct') {
      items.push({ type: 'struct', struct: node });
      i++;
    } else {
      i++;
    }
  }

  return items;
}

// ── Theorem + Proof → Lean theorem ──────────────────────────────────────────

function translateTheoremProof(thm: TheoremNode, proof: ProofNode): string {
  const name   = leanName(thm.name);
  const sig    = extractSignature(thm);
  const tactics = translateProofBody(proof.body);

  return [
    `theorem ${name} : ${sig} := by`,
    ...tactics.map(t => `  ${t}`),
    '',
  ].join('\n');
}

function translateTheoremOnly(thm: TheoremNode): string {
  const name = leanName(thm.name);
  const sig  = extractSignature(thm);
  return `theorem ${name} : ${sig} := by\n  sorry\n`;
}

function translateLemmaProof(lem: LemmaNode, proof: ProofNode): string {
  const name    = leanName(lem.name);
  const sig     = extractLemmaSignature(lem);
  const tactics = translateProofBody(proof.body);

  return [
    `lemma ${name} : ${sig} := by`,
    ...tactics.map(t => `  ${t}`),
    '',
  ].join('\n');
}

function translateDefinition(def: DefinitionNode): string {
  // Definitions in .fl are mathematical — emit as a noncomputable def or sorry
  const name = leanName(def.name);
  return `-- definition: ${def.name}\n-- noncomputable def ${name} := sorry\n`;
}

function translateStruct(s: StructNode): string {
  return `-- struct: ${s.name}\n`;
}

// ── Extract the proposition from a theorem's assert body ─────────────────────

function extractSignature(thm: TheoremNode): string {
  const asserts = thm.body.filter(n => n.type === 'Assert') as AssertNode[];
  if (asserts.length === 0) return 'True';
  // First assert is the main claim
  return rewriteExpr(asserts[0].expr);
}

function extractLemmaSignature(lem: LemmaNode): string {
  const asserts = lem.body.filter(n => n.type === 'Assert') as AssertNode[];
  if (asserts.length === 0) return 'True';
  return rewriteExpr(asserts[0].expr);
}

// ── Translate proof body nodes into Lean tactics ─────────────────────────────

function translateProofBody(nodes: ASTNode[]): string[] {
  const tactics: string[] = [];

  for (const node of nodes) {
    switch (node.type) {
      case 'SetVar': {
        const n = node as SetVarNode;
        if (n.varType) {
          // Typed variable → intro tactic or skip (Lean infers from context)
          const ltype = rewriteType(n.varType);
          if (n.value) {
            tactics.push(`have ${leanIdent(n.varName)} : ${ltype} := ${rewriteValue(n.value)}`);
          } else {
            tactics.push(`intro ${leanIdent(n.varName)}`);
          }
        } else if (n.value) {
          tactics.push(`have ${leanIdent(n.varName)} := ${rewriteValue(n.value)}`);
        }
        break;
      }

      case 'Assume': {
        const n = node as AssumeNode;
        const expr = rewriteExpr(n.expr);
        tactics.push(`intro h_${tactics.length}`);
        tactics.push(`-- assume: ${expr}`);
        break;
      }

      case 'Assert': {
        const n = node as AssertNode;
        const expr = rewriteExpr(n.expr);
        // Inside proof: each assert is a proof step
        if (isStringClaim(n.expr)) {
          tactics.push(`-- ${expr}`);
        } else {
          tactics.push(`have : ${expr} := by sorry`);
        }
        break;
      }

      case 'Apply': {
        const n = node as ApplyNode;
        tactics.push(`apply ${leanName(n.target.replace(/\(\)$/, ''))}`);
        break;
      }

      case 'Conclude': {
        const n = node as ConcludeNode;
        const expr = rewriteExpr(n.expr);
        if (isStringClaim(n.expr)) {
          tactics.push(`-- conclude: ${expr}`);
          tactics.push(`trivial`);
        } else {
          tactics.push(`exact by sorry -- ${expr}`);
        }
        break;
      }

      case 'Raw': {
        const n = node as RawNode;
        if (n.content.trim()) tactics.push(`-- ${n.content}`);
        break;
      }

      case 'Definition': {
        // Nested definition inside proof
        const n = node as DefinitionNode;
        tactics.push(`-- local def: ${n.name}`);
        break;
      }

      default:
        break;
    }
  }

  if (tactics.length === 0 || !tactics.some(t => !t.startsWith('--'))) {
    tactics.push('sorry');
  }

  return tactics;
}

// ── Math notation rewriter ───────────────────────────────────────────────────
// Converts .fl math notation to valid Lean 4 syntax.

function rewriteExpr(node: ExprNode): string {
  switch (node.type) {
    case 'Atom':    return rewriteAtom(node.condition);
    case 'And':     return `${rewriteExpr(node.left)} ∧ ${rewriteExpr(node.right)}`;
    case 'Or':      return `${rewriteExpr(node.left)} ∨ ${rewriteExpr(node.right)}`;
    case 'Implies': return `${rewriteExpr(node.left)} → ${rewriteExpr(node.right)}`;
    case 'Iff':     return `${rewriteExpr(node.left)} ↔ ${rewriteExpr(node.right)}`;
    case 'Not':     return `¬${rewriteExpr(node.operand)}`;
    default: return 'True';
  }
}

function rewriteAtom(s: string): string {
  // Strip surrounding quotes — string claims become True
  if ((s.startsWith('"') && s.endsWith('"')) ||
      (s.startsWith("'") && s.endsWith("'"))) {
    return 'True';
  }

  let r = s.trim();

  // Quantifier patterns: ∀(x: T) ⇒  →  ∀ x : T,
  r = r.replace(/∀\s*\(([^:)]+):\s*([^)]+)\)\s*[⇒→]/g, (_, v, t) =>
    `∀ ${leanIdent(v.trim())} : ${rewriteType(t.trim())},`);
  r = r.replace(/∃\s*\(([^:)]+):\s*([^)]+)\)\s*[⇒→]/g, (_, v, t) =>
    `∃ ${leanIdent(v.trim())} : ${rewriteType(t.trim())},`);

  // Multiple variables: ∀(a₁, a₂, ..., aₙ) ∈ ℝⁿ
  r = r.replace(/∀\s*\(([^)]+)\)\s*∈\s*(\S+)/g, (_, vars, set) => {
    const vs = vars.split(',').map((v: string) => leanIdent(v.trim()));
    return `∀ ${vs.join(' ')} : ${rewriteType(set)},`;
  });

  // Cardinality: |G| → G.card, |H| → H.card
  r = r.replace(/\|(\w+)\|/g, (_, g) => `${g}.card`);

  // Set notation rewrites
  r = r.replace(/divides/g, '∣');
  r = r.replace(/\bdivides\b/g, '∣');
  r = r.replace(/⊆/g, ' ⊆ ');

  // Type rewrites
  r = rewriteTypeInline(r);

  // ⇒ inside expressions → →
  r = r.replace(/⇒/g, '→');

  // Remaining subscript arrows
  r = r.replace(/→\s*→/g, '→');

  return r;
}

function rewriteType(t: string): string {
  const typeMap: Record<string, string> = {
    'ℝ': 'ℝ', 'ℕ': 'ℕ', 'ℤ': 'ℤ', 'ℚ': 'ℚ', '𝔹': 'Bool',
    'Vector': 'Vector ℝ n',
    'Group': 'Group',
    'Set': 'Set',
    'ℕ+': 'ℕ+',
    'Finset': 'Finset',
  };
  return typeMap[t.trim()] ?? t.trim();
}

function rewriteTypeInline(s: string): string {
  return s
    .replace(/\bℝⁿ\b/g, 'EuclideanSpace ℝ (Fin n)')
    .replace(/\bList\[ℝ\]/g, 'List ℝ')
    .replace(/\bSet@\{[^}]+\}/g, 'Set');
}

function rewriteValue(v: string): string {
  if (v === 'finite') return 'by assumption';
  if (/^\d+$/.test(v)) return v;
  return `sorry -- ${v}`;
}

function isStringClaim(expr: ExprNode): boolean {
  if (expr.type !== 'Atom') return false;
  const c = expr.condition.trim();
  return (c.startsWith('"') && c.endsWith('"')) ||
         (c.startsWith("'") && c.endsWith("'"));
}

// ── Identifier helpers ───────────────────────────────────────────────────────

function leanName(name: string): string {
  // Convert to snake_case, strip parens, handle subscripts
  return name
    .replace(/\(\)/g, '')
    .replace(/\s+/g, '_')
    .replace(/[^a-zA-Z0-9_αβγδεζηθικλμνξπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΠΡΣΤΥΦΧΨΩ₀-₉ₐ-ₙ']/g, '_');
}

function leanIdent(s: string): string {
  return s.replace(/[^a-zA-Z0-9_'₀-₉ₐ-ₙ]/g, '_').replace(/^_+/, '') || 'x';
}
